services:
  - type: web
    name: vochatk
    env: node
    buildCommand: |
      npm cache clean --force
      rm -rf node_modules
      rm -rf .next
      find . -name "next.config.ts" -type f -delete
      find . -name "tailwind.config.ts" -type f -delete
      find . -name "postcss.config.mjs" -type f -delete
      npm ci
      NODE_ENV=production npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://dpewvagbzhhrpplvphui.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwZXd2YWdiemhocnBwbHZwaHVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzNjQ4NDEsImV4cCI6MjA1MDk0MDg0MX0.aO4yJ_funzHT95b8VwLyvvOtHmzLIIRbZZCktCEYuPs
      - key: POSTGRES_DATABASE
        value: postgres
      - key: POSTGRES_HOST
        value: db.dpewvagbzhhrpplvphui.supabase.co
      - key: POSTGRES_USER
        value: postgres
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: POSTGRES_URL
        sync: false
      - key: POSTGRES_PRISMA_URL
        sync: false
      - key: POSTGRES_URL_NON_POOLING
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: PORT
        value: 3000
    autoDeploy: true
    healthCheckPath: /api/health
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 60
    buildFilter:
      paths:
        - src/**/*.ts
        - src/**/*.tsx
        - package.json
        - next.config.js
        - tailwind.config.js
        - postcss.config.js
        - tsconfig.json
