services:
  - type: web
    name: vochatk
    env: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: starter
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: POSTGRES_URL
        sync: false
      - key: POSTGRES_PRISMA_URL
        sync: false
      - key: POSTGRES_URL_NON_POOLING
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DATABASE
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
    healthCheckPath: /api/health
    healthCheckTimeout: 100
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
      targetCPUPercent: 80
    buildFilter:
      paths:
        - src/**/*.ts
        - src/**/*.tsx
        - package.json
        - next.config.js
        - tailwind.config.js
        - postcss.config.js
        - tsconfig.json
